name: auto-cli-py
channels:
    - anaconda
    - conda-forge
    - defaults
dependencies:
    - blas=1.0
    - boto3=1.9.130
    - ca-certificates=2019.1.23
    - certifi=2018.11.29
    - cython=0.29.7
    - intel-openmp=2019.1
    - libedit=3.1.20181209
    - libffi=3.2.1
    - libiconv=1.15
    - mkl=2019.1
    - mkl_fft=1.0.10
    - mkl_random=1.0.2
    - ncurses=6.1
    - numpy=1.16.2
    - numpy-base=1.16.2
    - openssl=1.1.1b
    - pandas=0.24.2
    - pip=19.0.3
    - pycparser=2.19
    - pylint=2.3.1
    - pymssql=2.1.4
    - pytest=4.3.1
    - python=3.7.2
    - readline=7.0
    - setuptools=40.8.0
    - sqlite=3.26.0
    - tk=8.6.8
    - unixodbc=2.3.7
    - wheel=0.33.1
    - xz=5.2.4
    - zlib=1.2.11
    - pip:
          - click==7.0
          - httpimport==0.5.16
          - itsdangerous==1.1.0
          - markdown==3.0.1
          - markupsafe==1.1.1
          - pytest-check==0.3.5
          - scipy==1.2.1
          - six==1.12.0
          - spacy==2.1.8
          - thinc==7.0.4
